# Use the official AWS Lambda Python image as the base
FROM public.ecr.aws/lambda/python:3.9

# Set working directory inside the container
WORKDIR /app

# Copy requirements and install them
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application source code
COPY src /app/src

# Set the CMD to your Lambda handler (e.g., app.lambda_handler)
CMD ["src.handlers.app.lambda_handler"]
